import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { RefreshCw, Copy, Download, CheckCircle2 } from "lucide-react";
import { useState } from "react";

export interface CapstoneResult {
  title: string;
  description: string;
  features: string[];
  techStack: string[];
  methodology?: string;
}

interface ResultCardProps {
  result: CapstoneResult;
  onRegenerate: () => void;
  isLoading: boolean;
}

const ResultCard = ({ result, onRegenerate, isLoading }: ResultCardProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const text = `Title: ${result.title}\n\nDescription: ${result.description}\n\nFeatures:\n${result.features.map((f) => `- ${f}`).join("\n")}\n\nTech Stack: ${result.techStack.join(", ")}${result.methodology ? `\n\nMethodology: ${result.methodology}` : ""}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = `CAPSTONE PROJECT PROPOSAL\n${"=".repeat(40)}\n\nTitle: ${result.title}\n\nDescription:\n${result.description}\n\nKey Features:\n${result.features.map((f) => `  • ${f}`).join("\n")}\n\nTech Stack:\n${result.techStack.map((t) => `  • ${t}`).join("\n")}${result.methodology ? `\n\nMethodology:\n${result.methodology}` : ""}\n\n${"=".repeat(40)}\nGenerated by Capstone Idea Generator`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `capstone-idea-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className="w-full max-w-2xl mx-auto"
    >
      <div className="rounded-2xl border border-border bg-card shadow-card overflow-hidden">
        {/* Header */}
        <div className="gradient-hero px-6 py-5">
          <h3 className="text-xl font-bold text-primary-foreground font-display">
            🏷️ {result.title}
          </h3>
        </div>

        <div className="p-6 space-y-5">
          {/* Description */}
          <div>
            <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">
              📄 Description
            </h4>
            <p className="text-foreground leading-relaxed">{result.description}</p>
          </div>

          {/* Features */}
          <div>
            <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">
              ⚙️ Features
            </h4>
            <ul className="space-y-2">
              {result.features.map((feature, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 * i }}
                  className="flex items-start gap-2 text-foreground"
                >
                  <CheckCircle2 className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <span>{feature}</span>
                </motion.li>
              ))}
            </ul>
          </div>

          {/* Tech Stack */}
          <div>
            <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">
              🧰 Tech Stack
            </h4>
            <div className="flex flex-wrap gap-2">
              {result.techStack.map((tech) => (
                <span
                  key={tech}
                  className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-medium"
                >
                  {tech}
                </span>
              ))}
            </div>
          </div>

          {/* Methodology */}
          {result.methodology && (
            <div>
              <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                🔬 Methodology
              </h4>
              <p className="text-foreground leading-relaxed">{result.methodology}</p>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="px-6 py-4 border-t border-border flex flex-wrap gap-3">
          <Button variant="default" size="default" onClick={onRegenerate} disabled={isLoading}>
            <RefreshCw className={`h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
            Regenerate
          </Button>
          <Button variant="outline" size="default" onClick={handleCopy}>
            <Copy className="h-4 w-4" />
            {copied ? "Copied!" : "Copy"}
          </Button>
          <Button variant="outline" size="default" onClick={handleDownload}>
            <Download className="h-4 w-4" />
            Download
          </Button>
        </div>
      </div>
    </motion.div>
  );
};

export default ResultCard;
